backend:
  name: github
  repo: colorlessenergy/brians-kitchen # Path to your Github repository
  branch: master # Branch to update


media_folder: "imgs"

collections:
  - name: "recipes" # Used in routes, e.g., /admin/collections/blog
    label: "recipes" # Used in the UI
    folder: "_recipes" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "title of the item", name: "title", widget: "string"}
      - {label: "price of the item", name: "item-price", widget: "number"}
      - {label: "picture of the item", name: "item-picture", widget: "image"}
      - {label: "the image of the product, that will show up on the cms", name: "thumbnail", widget: "image"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "details"}
      - {label: "categories of the item", name: "categories", widget: "string"}
      - {label: "ingredients of the item", name: "ingredients", widget: "text"}
      - {label: "description of the item", name: "description", widget: "text"}

  - name: "about" # Used in routes, e.g., /admin/collections/blog
    label: "about" # Used in the UI
    folder: "_about" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., title.md
    fields: # The fields for each document, usually in front matter
      - {label: "title", name: "title", widget: "string"}
      - {label: "picture", name: "picture", widget: "image"}
      - {label: "picture, that will show up on the cms", name: "thumbnail", widget: "image"}
      - {label: "Bio", name: "meta", widget: "text"}
      - {label: "description", name: "description", widget: "text"}
